### ISSUE TITLE
Consider adding formatting to logger

### ISSUE THREAD

**Issue by mutantcornholio** [paritytech/opstooling-js#15]
One more thing that I kinda want to bring here from my previous experience is log formatting function.

we added `util.format` to our logging function by default, and also added special `%L` substitution, which expands to `util.inspect(item, { showHidden: false, depth: null, maxArrayLength: null, sorted: true })`, which 
* doesn't produce `[object Object]`
* shows deep nested properties
* doesn't do `  ... 399 more items ]` thing. 

We used it like this: 
```ts
logger.info('result: %L', someObject)
```

While I was never a fan of formatting functions in programming, and always preferred template literals (or similar alternatives), I found this one to be extremely useful.  
We also supported all other `format` substitutions like `%d`, `%j` or `%o`, but I don't think that we really used them.  

One caveat would be that substitution might get triggered when `%` sign is used in the string that gets logged. I don't expect cases like this to take place, but an option to avoid those could be adding an option to enable formatting, or maybe just to have separate methods with formatting.  
Something like this: 
```ts
logger.info("%L", "test") // Doesn't do formatting; outputs `%L test`
logger.infoWithFmt("%L", "test") // Does formatting; outputs `test`
```

@paritytech/opstooling WDYT?

**Comment by joao-paulo-parity** [comment]
Is there a downside to

```
logger.info(`result: ${formatLong(value)}`)
```

compared to this current approach? What are the tradeoffs you see?

I'm okay with the idea overall, just wondering if it's better to avoid creating a new API for this since it can be achieved through code with existing APIs. Using a function seems more type-safe and easier to remember.

**Comment by mutantcornholio** [comment]
> Is there a downside to
> 
> ```
> logger.info(`result: ${formatLong(value)}`)
> ```
> 
> compared to this current approach? What are the tradeoffs you see?
> 
> I'm okay with the idea overall, just wondering if it's better to avoid creating a new API for this since it can be achieved through code with existing APIs. Using a function seems more type-safe and easier to remember.

Actually, that's the way that I've been doing it at first, but the beauty of the suggested solution was its simplicity.  

If you have a logger, you have formatting enabled. If you need to import another function just for formatting, you start to consider, whether you actually need formatting in a particular usecase. Surprisingly, this was less error-prone (if you consider getting `[object Object]` in logs an error), as applying formatting to all data of unknown nature becomes a habit.  

I think, a compromise to consider could be, to make formatting a method of `logger`.  
Something like
```ts
logger.info(`result: ${logger.fmt(value)}`)
```

This way, to add a value to logging string, you wouldn't need to import anything.

**Comment by joao-paulo-parity** [comment]
> I think, a compromise to consider could be, to make formatting a method of `logger`.  
> Something like
```ts
logger.info(`result: ${logger.fmt(value)}`)
```

> This way, to add a value to logging string, you wouldn't need to import anything.

That's pretty good. For me it'd be the best option. So my ranking is:

1. `logger.formatLong(value)`
2. `formatLong(value)`
3. `logger.infoWithFmt("%L", "test")`

IMO all three are reasonable, although I think 1 and 2 are better in terms of

- Avoids creating more logging APIs
- Using functions to serialize data is common idiom in Node.js, thus they're easy to remember, as opposing to have to memorize what the `%format` expressions mean.
- Potentially more type-safe

**Comment by mutantcornholio** [comment]
@joao-paulo-parity going a bit off the topic, but what does "Long" in `formatLong` mean?  
Just curious :)

**Comment by joao-paulo-parity** [comment]
> @joao-paulo-parity going a bit off the topic, but what does "Long" in `formatLong` mean? Just curious :)

I was referring to, for the sake of the example, to `long` as in the C datatype (https://en.wikipedia.org/wiki/C_data_types#Main_types) since their format specifier startswith `%l` (lowercase, not uppercase like the example). To print `unsigned long` for example one would use `printf("%lu", value)`.

The name I chose has no meaning whatsoever outside of my example.

For printing JS objects I think good names could be `fmt`, `format`, `dump`, `verbose`, etc, but I have no preferences.

**Comment by joao-paulo-parity** [comment]
Just one thing to add: the logging API takes after the `pino` (https://github.com/pinojs/pino/blob/master/docs/api.md#loggerinfomergingobject-message-interpolationvalues) as in `method(item, message, ...extra)`. This makes sense since someone might want to log something without providing a message e.g. while prototyping or if the object itself already includes some sort of message.

So despite the example I showed of logger.info(\`result: ${logger.fmt(value)}\`) we don't actually have to deal with string interpolation at all; instead it would be `logger.info(logger.fmt(value), "Result"))`.
